name: CI

on:
  push:
    tags:        
      - v**

env:
    DOTNET_NOLOGO: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_VERSION: 6.0.100

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Cache NuGet packages
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Determine version from tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        strip_v: true

    - name: Build package (only .Net 6 version)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd src/Npgsql.Bulk.DotNet6
        dotnet pack -c Release /p:Version=${{ steps.tag.outputs.tag }} /p:PackageID=PitCrew.Npgsql.Bulk

    - name: NuGet Push using GPR
      run: |
        dotnet tool install --global --verbosity minimal --no-cache gpr
        gpr push \
          --api-key ${{ secrets.GITHUB_TOKEN }} \
          **/*.nupkg

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "**/*.nupkg"
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        allowUpdates: true
